webtalk_init -webtalk_dir C:/Users/hp/projet filtre/projet filtre.sim/sim_1/behav/xsim/xsim.dir/tb_lena_dupliq_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jan  1 18:56:17 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "cb0cb44b-ff94-40fc-8c5a-c3fe6d04e96b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0c4e0f55332d4199a81c77eedbd33c44" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "92" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2112 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3110485 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "5.92_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "17552_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2236503790 -regid "" -xml C:/Users/hp/projet filtre/projet filtre.sim/sim_1/behav/xsim/xsim.dir/tb_lena_dupliq_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/hp/projet filtre/projet filtre.sim/sim_1/behav/xsim/xsim.dir/tb_lena_dupliq_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/hp/projet filtre/projet filtre.sim/sim_1/behav/xsim/xsim.dir/tb_lena_dupliq_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
